import 'package:flutter/material.dart';

@immutable
class const AppColorsX(
  // {
  // required this.badgeBgPrimary,
  // required this.badgeBgSecondary,
  // required this.baseBgPrimaryInverse,
  // required this.badgeBorder,
  // required this.baseBgSecondary,
  // required this.bgSnackbar,
  // required this.bgTooltip,
  // required this.borderBrand,
  // required this.borderPrimary,
  // required this.borderSecondary,
  // required this.buttonBgDisabled,
  // required this.buttonBgSecondary,
  // required this.buttonBgSecondaryInverse,
  // required this.buttonBgTertiary,
  // required this.cellBgPrimary,
  // required this.cellBorderActive,
  // required this.iconAccent,
  // required this.iconDisabled,
  // required this.iconPrimary,
  // required this.iconPrimaryInverse,
  // required this.iconSecondary,
  // required this.iconTertiary,
  // required this.inputBgPrimary,
  // required this.inputBgSecondary,
  // required this.progressBar,
  // required this.selectCheckbox,
  // required this.tabBgPrimary,
  // required this.tabBgSecondary,
  // required this.textAccent,
  // required this.textDisabled,
  // required this.textPrimary,
  // required this.textPrimaryInverse,
  // required this.textSecondary,
  // required this.textSecondaryInverse,
  // required this.textTertiary,
  // required this.toggleBgDisabled,
  // required this.toggleBgSecondary,
  // required this.toggleHandle,
  // required this.toggleHandleDisabled,
  // required this.trackBar,
  // required this.baseBgPrimary,
  // required this.error,
  // required this.errorLight,
  // required this.warning,
  // required this.warningLight,
  // required this.success,
  // required this.successLight,
  // required this.info,
  // required this.infoLight,
  // required this.iosBase,
  // required this.iosModalStack,
  // required this.iosModalStackText,
  // required this.componentBorder,
  // required this.note,
  // required this.grabber,
  // }
) extends ThemeExtension<AppColorsX> {
  @override
  AppColorsX copyWith(
    // {
    // Color? badgeBgPrimary,
    // Color? badgeBgSecondary,
    // Color? baseBgPrimaryInverse,
    // Color? badgeBorder,
    // Color? baseBgSecondary,
    // Color? bgSnackbar,
    // Color? bgTooltip,
    // Color? borderBrand,
    // Color? borderPrimary,
    // Color? borderSecondary,
    // Color? buttonBgDisabled,
    // Color? buttonBgSecondary,
    // Color? buttonBgSecondaryInverse,
    // Color? buttonBgTertiary,
    // Color? cellBgPrimary,
    // Color? cellBorderActive,
    // Color? iconAccent,
    // Color? iconDisabled,
    // Color? iconPrimary,
    // Color? iconPrimaryInverse,
    // Color? iconSecondary,
    // Color? iconTertiary,
    // Color? inputBgPrimary,
    // Color? inputBgSecondary,
    // Color? progressBar,
    // Color? selectCheckbox,
    // Color? tabBgPrimary,
    // Color? tabBgSecondary,
    // Color? textAccent,
    // Color? textDisabled,
    // Color? textPrimary,
    // Color? textPrimaryInverse,
    // Color? textSecondary,
    // Color? textSecondaryInverse,
    // Color? textTertiary,
    // Color? toggleBgDisabled,
    // Color? toggleBgSecondary,
    // Color? toggleHandle,
    // Color? toggleHandleDisabled,
    // Color? trackBar,
    // Color? baseBgPrimary,
    // Color? error,
    // Color? errorLight,
    // Color? warning,
    // Color? warningLight,
    // Color? success,
    // Color? successLight,
    // Color? info,
    // Color? infoLight,
    // Color? iosBase,
    // Color? iosModalStack,
    // Color? iosModalStackText,
    // Color? componentBorder,
    // Color? note,
    // Color? grabber,
    // }
  ) => const AppColorsX(
    // badgeBgPrimary: badgeBgPrimary ?? this.badgeBgPrimary,
    // badgeBgSecondary: badgeBgSecondary ?? this.badgeBgSecondary,
    // baseBgPrimaryInverse: baseBgPrimaryInverse ?? this.baseBgPrimaryInverse,
    // badgeBorder: badgeBorder ?? this.badgeBorder,
    // baseBgSecondary: baseBgSecondary ?? this.baseBgSecondary,
    // bgSnackbar: bgSnackbar ?? this.bgSnackbar,
    // bgTooltip: bgTooltip ?? this.bgTooltip,
    // borderBrand: borderBrand ?? this.borderBrand,
    // borderPrimary: borderPrimary ?? this.borderPrimary,
    // borderSecondary: borderSecondary ?? this.borderSecondary,
    // buttonBgDisabled: buttonBgDisabled ?? this.buttonBgDisabled,
    // buttonBgSecondary: buttonBgSecondary ?? this.buttonBgSecondary,
    // buttonBgSecondaryInverse:
    //     buttonBgSecondaryInverse ?? this.buttonBgSecondaryInverse,
    // buttonBgTertiary: buttonBgTertiary ?? this.buttonBgTertiary,
    // cellBgPrimary: cellBgPrimary ?? this.cellBgPrimary,
    // cellBorderActive: cellBorderActive ?? this.cellBorderActive,
    // iconAccent: iconAccent ?? this.iconAccent,
    // iconDisabled: iconDisabled ?? this.iconDisabled,
    // iconPrimary: iconPrimary ?? this.iconPrimary,
    // iconPrimaryInverse: iconPrimaryInverse ?? this.iconPrimaryInverse,
    // iconSecondary: iconSecondary ?? this.iconSecondary,
    // iconTertiary: iconTertiary ?? this.iconTertiary,
    // inputBgPrimary: inputBgPrimary ?? this.inputBgPrimary,
    // inputBgSecondary: inputBgSecondary ?? this.inputBgSecondary,
    // progressBar: progressBar ?? this.progressBar,
    // selectCheckbox: selectCheckbox ?? this.selectCheckbox,
    // tabBgPrimary: tabBgPrimary ?? this.tabBgPrimary,
    // tabBgSecondary: tabBgSecondary ?? this.tabBgSecondary,
    // textAccent: textAccent ?? this.textAccent,
    // textDisabled: textDisabled ?? this.textDisabled,
    // textPrimary: textPrimary ?? this.textPrimary,
    // textPrimaryInverse: textPrimaryInverse ?? this.textPrimaryInverse,
    // textSecondary: textSecondary ?? this.textSecondary,
    // textSecondaryInverse: textSecondaryInverse ?? this.textSecondaryInverse,
    // textTertiary: textTertiary ?? this.textTertiary,
    // toggleBgDisabled: toggleBgDisabled ?? this.toggleBgDisabled,
    // toggleBgSecondary: toggleBgSecondary ?? this.toggleBgSecondary,
    // toggleHandle: toggleHandle ?? this.toggleHandle,
    // toggleHandleDisabled: toggleHandleDisabled ?? this.toggleHandleDisabled,
    // trackBar: trackBar ?? this.trackBar,
    // baseBgPrimary: baseBgPrimary ?? this.baseBgPrimary,
    // error: error ?? this.error,
    // errorLight: errorLight ?? this.errorLight,
    // warning: warning ?? this.warning,
    // warningLight: warningLight ?? this.warningLight,
    // success: success ?? this.success,
    // successLight: successLight ?? this.successLight,
    // info: info ?? this.info,
    // infoLight: infoLight ?? this.infoLight,
    // iosBase: iosBase ?? this.iosBase,
    // iosModalStack: iosModalStack ?? this.iosModalStack,
    // iosModalStackText: iosModalStackText ?? this.iosModalStackText,
    // componentBorder: componentBorder ?? this.componentBorder,
    // note: note ?? this.note,
    // grabber: grabber ?? this.grabber,
  );

  @override
  AppColorsX lerp(AppColorsX? other, double t) {
    if (other is! AppColorsX) {
      return this;
    }
    return const AppColorsX(
      // badgeBgPrimary: Color.lerp(badgeBgPrimary, other.badgeBgPrimary, t)!,
      // badgeBgSecondary:
      //     Color.lerp(badgeBgSecondary, other.badgeBgSecondary, t)!,
      // baseBgPrimaryInverse:
      //     Color.lerp(baseBgPrimaryInverse, other.baseBgPrimaryInverse, t)!,
      // badgeBorder: Color.lerp(badgeBorder, other.badgeBorder, t)!,
      // baseBgSecondary: Color.lerp(baseBgSecondary, other.baseBgSecondary, t)!,
      // bgSnackbar: Color.lerp(bgSnackbar, other.bgSnackbar, t)!,
      // bgTooltip: Color.lerp(bgTooltip, other.bgTooltip, t)!,
      // borderBrand: Color.lerp(borderBrand, other.borderBrand, t)!,
      // borderPrimary: Color.lerp(borderPrimary, other.borderPrimary, t)!,
      // borderSecondary: Color.lerp(borderSecondary, other.borderSecondary, t)!,
      // buttonBgDisabled:
      //     Color.lerp(buttonBgDisabled, other.buttonBgDisabled, t)!,
      // buttonBgSecondary:
      //     Color.lerp(buttonBgSecondary, other.buttonBgSecondary, t)!,
      // buttonBgSecondaryInverse: Color.lerp(
      //     buttonBgSecondaryInverse, other.buttonBgSecondaryInverse, t)!,
      // buttonBgTertiary:
      //     Color.lerp(buttonBgTertiary, other.buttonBgTertiary, t)!,
      // cellBgPrimary: Color.lerp(cellBgPrimary, other.cellBgPrimary, t)!,
      // cellBorderActive:
      //     Color.lerp(cellBorderActive, other.cellBorderActive, t)!,
      // iconAccent: Color.lerp(iconAccent, other.iconAccent, t)!,
      // iconDisabled: Color.lerp(iconDisabled, other.iconDisabled, t)!,
      // iconPrimary: Color.lerp(iconPrimary, other.iconPrimary, t)!,
      // iconPrimaryInverse:
      //     Color.lerp(iconPrimaryInverse, other.iconPrimaryInverse, t)!,
      // iconSecondary: Color.lerp(iconSecondary, other.iconSecondary, t)!,
      // iconTertiary: Color.lerp(iconTertiary, other.iconTertiary, t)!,
      // inputBgPrimary: Color.lerp(inputBgPrimary, other.inputBgPrimary, t)!,
      // inputBgSecondary:
      //     Color.lerp(inputBgSecondary, other.inputBgSecondary, t)!,
      // progressBar: Color.lerp(progressBar, other.progressBar, t)!,
      // selectCheckbox: Color.lerp(selectCheckbox, other.selectCheckbox, t)!,
      // tabBgPrimary: Color.lerp(tabBgPrimary, other.tabBgPrimary, t)!,
      // tabBgSecondary: Color.lerp(tabBgSecondary, other.tabBgSecondary, t)!,
      // textAccent: Color.lerp(textAccent, other.textAccent, t)!,
      // textDisabled: Color.lerp(textDisabled, other.textDisabled, t)!,
      // textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      // textPrimaryInverse:
      //     Color.lerp(textPrimaryInverse, other.textPrimaryInverse, t)!,
      // textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      // textSecondaryInverse:
      //     Color.lerp(textSecondaryInverse, other.textSecondaryInverse, t)!,
      // textTertiary: Color.lerp(textTertiary, other.textTertiary, t)!,
      // toggleBgDisabled:
      //     Color.lerp(toggleBgDisabled, other.toggleBgDisabled, t)!,
      // toggleBgSecondary:
      //     Color.lerp(toggleBgSecondary, other.toggleBgSecondary, t)!,
      // toggleHandle: Color.lerp(toggleHandle, other.toggleHandle, t)!,
      // toggleHandleDisabled:
      //     Color.lerp(toggleHandleDisabled, other.toggleHandleDisabled, t)!,
      // trackBar: Color.lerp(trackBar, other.trackBar, t)!,
      // baseBgPrimary: Color.lerp(baseBgPrimary, other.baseBgPrimary, t)!,
      // error: Color.lerp(error, other.error, t)!,
      // errorLight: Color.lerp(errorLight, other.errorLight, t)!,
      // warning: Color.lerp(warning, other.warning, t)!,
      // warningLight: Color.lerp(warningLight, other.warningLight, t)!,
      // success: Color.lerp(success, other.success, t)!,
      // successLight: Color.lerp(successLight, other.successLight, t)!,
      // info: Color.lerp(info, other.info, t)!,
      // infoLight: Color.lerp(infoLight, other.infoLight, t)!,
      // iosBase: Color.lerp(iosBase, other.iosBase, t)!,
      // iosModalStack: Color.lerp(iosModalStack, other.iosModalStack, t)!,
      // iosModalStackText:
      //     Color.lerp(iosModalStackText, other.iosModalStackText, t)!,
      // componentBorder: Color.lerp(componentBorder, other.componentBorder, t)!,
      // note: Color.lerp(note, other.note, t)!,
      // grabber: Color.lerp(grabber, other.grabber, t)!,
    );
  }
}
